using System;
using System.Collections.Generic;
using videoscriptAI.Models;

namespace videoscriptAI.Data
{
    public class Chat
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // Add these missing navigation properties
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

        public bool IsAutoGenerated { get; set; }

        public ICollection<ChatContent> ChatContents { get; set; } = new List<ChatContent>();
    }
}